### ISSUE TITLE
Sorry, you have been blocked

### ISSUE THREAD

**Issue by Castorice-1** [amclubs/am-cf-tunnel#3]
用不了了![屏幕截图 2024-11-27 171844](https://github.com/user-attachments/assets/0e421e31-a36e-43c2-9460-3e4203e1e963)

**Comment by amclubs** [comment]
你的域名可能给攻击,给限制了,换个其它名称的域名名称就可以

**Comment by Castorice-1** [comment]
> 您的域名可以给予攻击、给予限制，更换其他名称的域名就可以

我还没有绑定域名，应该是类似的项目被cloudfare给屏蔽了，我看其他的项目也有这个问题

**Comment by amclubs** [comment]
用最新的加密代码部署,或看这教程来解决 https://youtu.be/4fcyJjstFdg
